[package]
name = "grotto-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
ed25519-dalek.workspace = true
grotto-protocol.workspace = true
rcgen.workspace = true
rusqlite.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
